### ISSUE TITLE
Requesting an updated version for Plasma 6

### ISSUE THREAD

**Issue by Sojiro84** [acristoffers/kwin-rectangle#21] opened 2024-02-28 19:31 UTC
Hello,

As you maybe have noticed, Plasma 6 has been released today and your script needs to be updated for it to work for Plasma 6 it seems.

After upgrading, your script was gone (probably automatically done by KDE to be on the safe side after a big upgrade). I cant find it when looking for scripts from within KDE and installing the latest master from here gives this error:

`false
./install.sh: line 5: plasmapkg2: command not found
./install.sh: line 6: plasmapkg2: command not found
1`

I hope you can update the script. Been using it everyday since you have released it. Such a handy script that improves my productivity.

**Comment by acristoffers** [comment] 2024-02-28 21:43
Hi. Thank you for the issue and I'm glad you find the script useful.

I've updated the supporting files, so now it at least installs in Plasma 6, however it doesn't seem to work. When debugging, I cannot get the currently active (focused) window, even though the API website lists exactly the same functions as in Plasma 5, so it is either a problem in my machine or the docs need updating. This weekend I'll try to find scripts which already got updated so I can take a look at what changed. If you could just see if it works in your machine it would be great, as it working on your end would show the problem is somehow my setup.

**Comment by Sojiro84** [comment] 2024-02-28 21:52
Just tested it out. Installing initially didnt work seeing as the script folder was still present at "/home/USER/.local/share/kwin/scripts/".

Removed the files there and then ran the install.sh. Terminal said:

`false
Error: Plugin  is not installed.
Successfully installed /home/sojiro/.local/share/kwin/scripts/kwin-rectangle/
1`

Script did show up, disabled it, then enabled it again to make sure it was properly off and on, then checked the shortcuts to see if those where still present as well and then I tried the shortcuts but nothing was happening. So it seems something is slightly different.

Thanks for the quick response!

**Comment by Sojiro84** [comment] 2024-02-29 21:57
Tested out the script and works indeed! Thanks for the quick fix.

The store from within KDE is also showing up emtpy for me for scripts. Other sections do have content.

**Comment by acristoffers** [comment] 2024-03-01 10:27
The updated version is now listed on the store, even though nothing is listed in the Settings "Get More" interface. I'm closing the issue as the main pain-point was solved, and I'll see how I can report the possible regression in the numeric shortcuts upstream. Thank you for the issue and promptly feedback :)

**Closed by acristoffers** 2024-03-01 10:27 UTC
